/**
 * Generated by scripts/build_fixtures.py from data/. Do not edit.
 *
 * A Worker has no filesystem, so the rows have to travel in the bundle. Edit
 * the CSV and the JSON in data/, then run:
 *
 *     python3 scripts/build_fixtures.py
 *
 * CI runs `--check` and fails if this file and data/ have drifted apart.
 */


export const DESTINATIONS = [
  {
    "airport": "MAD",
    "city": "Madrid",
    "country": "Spain",
    "currency": "EUR",
    "bestMonths": "April–June, September–October",
    "summary": "Dense, walkable and late-running. The art is world class and the eating starts at 21:00.",
    "aliases": [
      "madrid",
      "spain"
    ],
    "neighbourhoods": [
      "Malasaña",
      "La Latina",
      "Chueca",
      "Salamanca",
      "Lavapiés"
    ],
    "highlights": [
      {
        "name": "Museo del Prado",
        "category": "sight",
        "note": "Go at opening or in the last free hours"
      },
      {
        "name": "Mercado de San Fernando",
        "category": "food",
        "note": "Cheaper and less touristed than San Miguel"
      },
      {
        "name": "Retiro Park",
        "category": "outdoors",
        "note": "Rowboats on the lake until 19:00"
      },
      {
        "name": "Toledo day trip",
        "category": "sight",
        "note": "33 minutes by AVE from Atocha"
      }
    ]
  },
  {
    "airport": "LIS",
    "city": "Lisbon",
    "country": "Portugal",
    "currency": "EUR",
    "bestMonths": "March–June, September–October",
    "summary": "Hills, tiles and light. Plan for the gradients — the trams exist for a reason.",
    "aliases": [
      "lisbon",
      "lisboa",
      "portugal"
    ],
    "neighbourhoods": [
      "Alfama",
      "Príncipe Real",
      "Baixa",
      "Graça",
      "Cais do Sodré"
    ],
    "highlights": [
      {
        "name": "Alfama at dawn",
        "category": "sight",
        "note": "Empty streets before the tour groups"
      },
      {
        "name": "Time Out Market",
        "category": "food",
        "note": "Busy at 13:00; go at 11:30"
      },
      {
        "name": "Sintra",
        "category": "sight",
        "note": "A full day, and book Pena Palace ahead"
      },
      {
        "name": "Belém",
        "category": "food",
        "note": "The pastéis really are better at the original"
      }
    ]
  },
  {
    "airport": "CDG",
    "city": "Paris",
    "country": "France",
    "currency": "EUR",
    "bestMonths": "April–June, September–October",
    "summary": "Everything you expect, plus a lot that only shows up if you walk between the sights.",
    "aliases": [
      "paris",
      "france"
    ],
    "neighbourhoods": [
      "Le Marais",
      "Canal Saint-Martin",
      "Saint-Germain",
      "Belleville"
    ],
    "highlights": [
      {
        "name": "Musée d’Orsay",
        "category": "sight",
        "note": "Better than the Louvre for a first visit"
      },
      {
        "name": "Canal Saint-Martin",
        "category": "outdoors",
        "note": "Sunday, when the roads close"
      },
      {
        "name": "Marché d’Aligre",
        "category": "food",
        "note": "Morning market, closed Mondays"
      }
    ]
  },
  {
    "airport": "NRT",
    "city": "Tokyo",
    "country": "Japan",
    "currency": "JPY",
    "bestMonths": "March–May, October–November",
    "summary": "Vast and legible at once. Pick two neighbourhoods a day and do them properly.",
    "aliases": [
      "tokyo",
      "japan"
    ],
    "neighbourhoods": [
      "Shibuya",
      "Yanaka",
      "Nakameguro",
      "Kagurazaka"
    ],
    "highlights": [
      {
        "name": "Tsukiji outer market",
        "category": "food",
        "note": "Before 09:00 or not at all"
      },
      {
        "name": "Shimokitazawa",
        "category": "shopping",
        "note": "Second-hand, coffee, small venues"
      },
      {
        "name": "Meiji Jingu",
        "category": "outdoors",
        "note": "Enter from Harajuku, leave via Yoyogi"
      }
    ]
  },
  {
    "airport": "MEX",
    "city": "Mexico City",
    "country": "Mexico",
    "currency": "MXN",
    "bestMonths": "March–May, October–November",
    "summary": "A capital that rewards a slow itinerary. Altitude is real on the first day.",
    "aliases": [
      "mexico city",
      "cdmx",
      "mexico"
    ],
    "neighbourhoods": [
      "Roma Norte",
      "Condesa",
      "Juárez",
      "Coyoacán"
    ],
    "highlights": [
      {
        "name": "Museo Nacional de Antropología",
        "category": "sight",
        "note": "Half a day, minimum"
      },
      {
        "name": "Mercado de Coyoacán",
        "category": "food",
        "note": "Tostadas, then the Frida Kahlo house"
      },
      {
        "name": "Roma Norte",
        "category": "food",
        "note": "Where to eat every evening"
      }
    ]
  },
  {
    "airport": "JFK",
    "city": "New York",
    "country": "United States",
    "currency": "USD",
    "bestMonths": "April–June, September–early November",
    "summary": "Walkable in bursts, and the subway covers the rest. Book nothing for the first evening.",
    "aliases": [
      "new york",
      "nyc",
      "manhattan",
      "brooklyn"
    ],
    "neighbourhoods": [
      "West Village",
      "Lower East Side",
      "Fort Greene",
      "Harlem",
      "Astoria"
    ],
    "highlights": [
      {
        "name": "The Met",
        "category": "sight",
        "note": "Enter at 10:00 and start on the top floor"
      },
      {
        "name": "Prospect Park",
        "category": "outdoors",
        "note": "Quieter than Central Park and better for a Saturday"
      },
      {
        "name": "Essex Market",
        "category": "food",
        "note": "Lunch, then walk the Williamsburg Bridge"
      },
      {
        "name": "The Frick",
        "category": "sight",
        "note": "One hour, and the best small collection in the city"
      }
    ]
  },
  {
    "airport": "ORD",
    "city": "Chicago",
    "country": "United States",
    "currency": "USD",
    "bestMonths": "May–June, September–October",
    "summary": "The best architecture in the country and a lakefront to walk it off on. Winter is not a suggestion.",
    "aliases": [
      "chicago",
      "chi"
    ],
    "neighbourhoods": [
      "Wicker Park",
      "Logan Square",
      "Pilsen",
      "Hyde Park",
      "Andersonville"
    ],
    "highlights": [
      {
        "name": "Chicago Architecture river cruise",
        "category": "sight",
        "note": "Do it first; everything else makes more sense after"
      },
      {
        "name": "Art Institute",
        "category": "sight",
        "note": "The Thorne Rooms are worth the detour"
      },
      {
        "name": "Pilsen",
        "category": "food",
        "note": "Murals, then tacos on 18th Street"
      }
    ]
  },
  {
    "airport": "SFO",
    "city": "San Francisco",
    "country": "United States",
    "currency": "USD",
    "bestMonths": "September–October",
    "summary": "Small, steep and a dozen microclimates. Bring a layer even in August — especially in August.",
    "aliases": [
      "san francisco",
      "sf",
      "bay area"
    ],
    "neighbourhoods": [
      "Mission",
      "Hayes Valley",
      "North Beach",
      "Outer Sunset",
      "Potrero Hill"
    ],
    "highlights": [
      {
        "name": "Lands End",
        "category": "outdoors",
        "note": "The coastal trail, ending at the Sutro Baths"
      },
      {
        "name": "Ferry Building",
        "category": "food",
        "note": "Saturday market before 10:00"
      },
      {
        "name": "Mission murals",
        "category": "sight",
        "note": "Balmy Alley and Clarion Alley, half an hour apart"
      }
    ]
  },
  {
    "airport": "ATH",
    "city": "Athens",
    "country": "Greece",
    "currency": "EUR",
    "bestMonths": "April–June, September–October",
    "summary": "Ancient and scruffy and excellent. The islands are two hours away when you want them.",
    "aliases": [
      "athens",
      "greece"
    ],
    "neighbourhoods": [
      "Koukaki",
      "Plaka",
      "Exarchia",
      "Kolonaki"
    ],
    "highlights": [
      {
        "name": "Acropolis",
        "category": "sight",
        "note": "First entry slot, before the heat"
      },
      {
        "name": "Anafiotika",
        "category": "sight",
        "note": "Island village inside the city"
      },
      {
        "name": "Varvakios market",
        "category": "food",
        "note": "Not for the squeamish; superb"
      }
    ]
  }
] as const;

export const AIRLINES = [
  {
    "code": "IB",
    "name": "Iberia"
  },
  {
    "code": "DL",
    "name": "Delta"
  },
  {
    "code": "TP",
    "name": "TAP Air Portugal"
  },
  {
    "code": "AF",
    "name": "Air France"
  },
  {
    "code": "UA",
    "name": "United"
  },
  {
    "code": "LH",
    "name": "Lufthansa"
  },
  {
    "code": "AA",
    "name": "American"
  }
] as const;

export const ORIGINS = [
  {
    "code": "JFK",
    "city": "New York",
    "zones": [
      "America/New_York",
      "America/Detroit",
      "America/Toronto"
    ]
  },
  {
    "code": "ORD",
    "city": "Chicago",
    "zones": [
      "America/Chicago",
      "America/Winnipeg"
    ]
  },
  {
    "code": "DEN",
    "city": "Denver",
    "zones": [
      "America/Denver",
      "America/Edmonton",
      "America/Phoenix"
    ]
  },
  {
    "code": "LAX",
    "city": "Los Angeles",
    "zones": [
      "America/Los_Angeles",
      "America/Vancouver",
      "America/Tijuana"
    ]
  },
  {
    "code": "MIA",
    "city": "Miami",
    "zones": [
      "America/Bogota",
      "America/Lima",
      "America/Panama"
    ]
  },
  {
    "code": "GRU",
    "city": "São Paulo",
    "zones": [
      "America/Sao_Paulo",
      "America/Argentina/Buenos_Aires"
    ]
  },
  {
    "code": "LHR",
    "city": "London",
    "zones": [
      "Europe/London",
      "Europe/Dublin",
      "Europe/Lisbon"
    ]
  },
  {
    "code": "CDG",
    "city": "Paris",
    "zones": [
      "Europe/Paris",
      "Europe/Brussels",
      "Europe/Madrid",
      "Europe/Amsterdam"
    ]
  },
  {
    "code": "FRA",
    "city": "Frankfurt",
    "zones": [
      "Europe/Berlin",
      "Europe/Zurich",
      "Europe/Vienna",
      "Europe/Prague",
      "Europe/Rome"
    ]
  },
  {
    "code": "DXB",
    "city": "Dubai",
    "zones": [
      "Asia/Dubai",
      "Asia/Riyadh",
      "Asia/Qatar"
    ]
  },
  {
    "code": "DEL",
    "city": "Delhi",
    "zones": [
      "Asia/Kolkata",
      "Asia/Calcutta",
      "Asia/Karachi",
      "Asia/Kathmandu"
    ]
  },
  {
    "code": "SIN",
    "city": "Singapore",
    "zones": [
      "Asia/Singapore",
      "Asia/Kuala_Lumpur",
      "Asia/Jakarta",
      "Asia/Bangkok"
    ]
  },
  {
    "code": "HKG",
    "city": "Hong Kong",
    "zones": [
      "Asia/Hong_Kong",
      "Asia/Shanghai",
      "Asia/Taipei",
      "Asia/Manila"
    ]
  },
  {
    "code": "NRT",
    "city": "Tokyo",
    "zones": [
      "Asia/Tokyo",
      "Asia/Seoul"
    ]
  },
  {
    "code": "SYD",
    "city": "Sydney",
    "zones": [
      "Australia/Sydney",
      "Australia/Melbourne",
      "Australia/Brisbane"
    ]
  },
  {
    "code": "JNB",
    "city": "Johannesburg",
    "zones": [
      "Africa/Johannesburg",
      "Africa/Nairobi",
      "Africa/Lagos"
    ]
  }
] as const;

export const CURRENCY_SYMBOL = {
  "EUR": "€",
  "USD": "$",
  "JPY": "¥",
  "MXN": "MX$",
  "GBP": "£"
} as const;

export const HOTEL_WORDS = [
  "Casa",
  "Hotel",
  "Residencia",
  "The",
  "Pensão",
  "Villa"
] as const;

export const HOTEL_NAMES = [
  "Aurora",
  "Verano",
  "Miradouro",
  "Barrio",
  "Lumière",
  "Alta",
  "Nueve",
  "Bruma"
] as const;

export const AMENITIES = [
  "Breakfast",
  "Rooftop",
  "Air-con",
  "Kitchenette",
  "Late check-out",
  "Bikes",
  "Laundry"
] as const;

export const CONNECTIONS = [
  "LIS",
  "LHR",
  "CDG",
  "AMS",
  "FRA"
] as const;
