#!/usr/bin/env python3
"""Compiles `data/` into a module the Worker can import.

A Cloudflare Worker has no filesystem, so a CSV it needs at request time has to
be in the bundle. This is the step that puts it there, and the shape is the one
a real application uses: seed data lives in a portable format a person can edit,
a build turns it into something the runtime can load, and CI fails when the two
disagree.

The Python backend reads `data/` directly with the `csv` module — no build step,
because it has a filesystem. Same rows, same fixtures, one source of truth.

    python3 scripts/build_fixtures.py            # write
    python3 scripts/build_fixtures.py --check    # fail if what is on disk is stale
"""

from __future__ import annotations

import argparse
import csv
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "apps" / "worker" / "src" / "providers" / "fixtures.generated.ts"

BANNER = """\
/**
 * Generated by scripts/build_fixtures.py from data/. Do not edit.
 *
 * A Worker has no filesystem, so the rows have to travel in the bundle. Edit
 * the CSV and the JSON in data/, then run:
 *
 *     python3 scripts/build_fixtures.py
 *
 * CI runs `--check` and fails if this file and data/ have drifted apart.
 */
"""


def read_csv(name: str) -> list[dict[str, str]]:
    """Rows from a CSV, with `#` comment lines skipped.

    `csv.DictReader` has no notion of a comment, and the comments in these files
    are load-bearing — they are the only place that records that row order seeds
    the picker. So they are stripped here rather than removed from the data.
    """
    path = DATA / name
    if not path.exists():
        raise SystemExit(f"Missing data file: {path.relative_to(ROOT)}")
    lines = [line for line in path.read_text("utf-8").splitlines() if not line.startswith("#")]
    return [dict(row) for row in csv.DictReader(lines)]


def build() -> str:
    destinations = json.loads((DATA / "destinations.json").read_text("utf-8"))["destinations"]

    airlines = [{"code": r["code"], "name": r["name"]} for r in read_csv("airlines.csv")]
    origins = [
        {"code": r["code"], "city": r["city"], "zones": r["zones"].split("|")}
        for r in read_csv("origins.csv")
    ]
    currencies = {r["code"]: r["symbol"] for r in read_csv("currencies.csv")}

    lodging: dict[str, list[str]] = {}
    for row in read_csv("lodging.csv"):
        lodging.setdefault(row["kind"], []).append(row["value"])

    # Every list below seeds a deterministic picker. An empty one would not throw
    # — it would silently produce a hotel called "undefined undefined" — so the
    # build refuses rather than the demo degrading.
    for label, rows in [
        ("destinations.json", destinations),
        ("airlines.csv", airlines),
        ("origins.csv", origins),
        ("currencies.csv", list(currencies)),
        *[(f"lodging.csv ({kind})", lodging.get(kind, [])) for kind in
          ("word", "name", "amenity", "connection")],
    ]:
        if not rows:
            raise SystemExit(f"{label} is empty. A fixture source with no rows is a broken demo.")

    def emit(name: str, value: object) -> str:
        return f"export const {name} = {json.dumps(value, indent=2, ensure_ascii=False)} as const;\n"

    parts = [
        BANNER,
        "",
        emit("DESTINATIONS", destinations),
        emit("AIRLINES", airlines),
        emit("ORIGINS", origins),
        emit("CURRENCY_SYMBOL", currencies),
        emit("HOTEL_WORDS", lodging["word"]),
        emit("HOTEL_NAMES", lodging["name"]),
        emit("AMENITIES", lodging["amenity"]),
        emit("CONNECTIONS", lodging["connection"]),
    ]
    return "\n".join(parts)


def main() -> int:
    args = argparse.ArgumentParser(description=__doc__)
    args.add_argument("--check", action="store_true", help="Do not write; fail if stale.")
    options = args.parse_args()

    body = build()

    if options.check:
        if not OUT.exists() or OUT.read_text("utf-8") != body:
            print(f"{OUT.relative_to(ROOT)} is stale.", file=sys.stderr)
            print("Regenerate with: python3 scripts/build_fixtures.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date with data/.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} from data/.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
